package update

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/rs/zerolog/log"
)

// SelfHeal performs runtime self-healing operations.
func SelfHeal() error {
	var errors []string

	// 1. Ensure runtime directory exists
	if err := ensureRuntimeDir(); err != nil {
		errors = append(errors, fmt.Sprintf("runtime dir: %v", err))
	}

	// 2. Self-heal environment variables
	if err := selfHealEnv(); err != nil {
		errors = append(errors, fmt.Sprintf("env: %v", err))
	}

	// 3. Self-heal nginx configuration
	if err := selfHealNginx(); err != nil {
		errors = append(errors, fmt.Sprintf("nginx: %v", err))
	}

	// 4. Ensure directories exist
	if err := EnsurePathsExist(); err != nil {
		errors = append(errors, fmt.Sprintf("directories: %v", err))
	}

	// 5. Reload systemd if needed
	if err := reloadSystemd(); err != nil {
		errors = append(errors, fmt.Sprintf("systemd reload: %v", err))
	}

	// 6. Verify health
	if err := VerifyHealth(); err != nil {
		errors = append(errors, fmt.Sprintf("health: %v", err))
	}

	if len(errors) > 0 {
		return fmt.Errorf("self-heal completed with errors: %s", strings.Join(errors, "; "))
	}

	log.Info().Msg("Self-heal completed successfully")
	return nil
}

// ensureRuntimeDir ensures /run/orvixpanel exists.
func ensureRuntimeDir() error {
	runDir := "/run/orvixpanel"
	if err := os.MkdirAll(runDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", runDir, err)
	}
	return nil
}

// selfHealEnv ensures required environment variables are set.
func selfHealEnv() error {
	p := GetInstallPaths()
	envFile := p.EnvFile

	// Ensure env file exists
	if _, err := os.Stat(envFile); os.IsNotExist(err) {
		if err := createDefaultEnvFile(envFile); err != nil {
			return fmt.Errorf("create env file: %w", err)
		}
	}

	// Read current env
	data, err := os.ReadFile(envFile)
	if err != nil {
		return fmt.Errorf("read env file: %w", err)
	}

	lines := strings.Split(string(data), "\n")
	envVars := make(map[string]string)
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if idx := strings.Index(line, "="); idx > 0 {
			key := strings.TrimSpace(line[:idx])
			value := strings.TrimSpace(line[idx+1:])
			envVars[key] = value
		}
	}

	modified := false

	// Check ORVIX_SERVER_SECRET_KEY
	if _, ok := envVars["ORVIX_SERVER_SECRET_KEY"]; !ok {
		secret := generateSecret(32)
		envVars["ORVIX_SERVER_SECRET_KEY"] = secret
		modified = true
		log.Info().Msg("Generated ORVIX_SERVER_SECRET_KEY")
	}

	// Check ORVIX_FRONTEND_DIST
	if _, ok := envVars["ORVIX_FRONTEND_DIST"]; !ok {
		defaultPath := filepath.Join(p.Var, "www", "orvixpanel")
		if _, err := os.Stat(defaultPath); err == nil {
			envVars["ORVIX_FRONTEND_DIST"] = defaultPath
			modified = true
			log.Info().Str("path", defaultPath).Msg("Set ORVIX_FRONTEND_DIST")
		}
	}

	// Write back if modified
	if modified {
		var newLines []string
		for k, v := range envVars {
			newLines = append(newLines, fmt.Sprintf("%s=%s", k, v))
		}
		os.WriteFile(envFile, []byte(strings.Join(newLines, "\n")), 0o644)
	}

	return nil
}

// createDefaultEnvFile creates a default .env file.
func createDefaultEnvFile(path string) error {
	p := GetInstallPaths()

	content := fmt.Sprintf(`# OrvixPanel Environment Configuration
# Generated by update engine

# Server Configuration
ORVIX_SERVER_SECRET_KEY=%s
ORVIX_BIND=0.0.0.0
ORVIX_PORT=8080

# Frontend
ORVIX_FRONTEND_DIST=%s/www/orvixpanel

# Database
ORVIX_DB_PATH=%s/orvixpanel.db

# Debug (set to 1 for development only)
ORVIX_DEBUG=0
`, generateSecret(32), p.Var, p.Var)

	return os.WriteFile(path, []byte(content), 0o600)
}

func generateSecret(length int) string {
	// Use /dev/urandom for secure random
	cmd := exec.Command("sh", "-c", fmt.Sprintf("head -c %d /dev/urandom | base64 | tr -d '\\n'", length))
	if output, err := cmd.Output(); err == nil {
		result := strings.TrimSpace(string(output))
		if len(result) >= length {
			return result[:length]
		}
	}

	// Fallback to a simpler method
	chars := "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	result := make([]byte, length)
	for i := range result {
		result[i] = chars[i%len(chars)]
	}
	return string(result)
}

// selfHealNginx fixes common nginx configuration issues.
func selfHealNginx() error {
	sitesEnabled := "/etc/nginx/sites-enabled"
	if _, err := os.Stat(sitesEnabled); err != nil {
		return nil // nginx not configured, skip
	}

	entries, err := os.ReadDir(sitesEnabled)
	if err != nil {
		return nil
	}

	// Find all configs with default_server
	defaultServers := make(map[string]string)
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		path := filepath.Join(sitesEnabled, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if bytes.Contains(data, []byte("default_server")) {
			defaultServers[entry.Name()] = path
		}
	}

	// If multiple default_server, keep the first alphabetically and warn
	if len(defaultServers) > 1 {
		log.Warn().Int("count", len(defaultServers)).Msg("Multiple default_server found in nginx config")
		// We don't auto-fix to avoid breaking existing configs
		// Just log a warning
	}

	// Check for conflicting port 80/443 bindings
	if err := checkNginxPorts(); err != nil {
		log.Warn().Err(err).Msg("nginx port conflict detected")
	}

	// Test and reload nginx if needed
	cmd := exec.Command("nginx", "-t")
	cmd.Stdout = &bytes.Buffer{}
	cmd.Stderr = &bytes.Buffer{}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("nginx -t failed: %w", err)
	}

	return nil
}

// checkNginxPorts checks for port binding conflicts.
func checkNginxPorts() error {
	// This is a best-effort check
	// We look for obvious issues but don't do deep analysis

	sitesAvailable := "/etc/nginx/sites-available"
	sitesEnabled := "/etc/nginx/sites-enabled"

	if _, err := os.Stat(sitesAvailable); err != nil {
		return nil
	}

	// Read all enabled sites and check for duplicate server_name directives
	entries, err := os.ReadDir(sitesEnabled)
	if err != nil {
		return nil
	}

	serverNames := make(map[string][]string)
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		path := filepath.Join(sitesEnabled, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}

		// Simple extraction of server_name
		lines := strings.Split(string(data), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "server_name") {
				value := strings.TrimPrefix(line, "server_name")
				value = strings.TrimSuffix(value, ";")
				value = strings.TrimSpace(value)
				serverNames[value] = append(serverNames[value], entry.Name())
			}
		}
	}

	// Check for duplicates
	for sn, files := range serverNames {
		if len(files) > 1 {
			return fmt.Errorf("duplicate server_name '%s' in %v", sn, files)
		}
	}

	return nil
}

// reloadSystemd reloads the systemd daemon.
func reloadSystemd() error {
	cmd := exec.Command("systemctl", "daemon-reload")
	cmd.Stdout = &bytes.Buffer{}
	cmd.Stderr = &bytes.Buffer{}
	return cmd.Run()
}

// VerifyHealth verifies the service is healthy after restart.
func VerifyHealth() error {
	// Get the health endpoint from runtime config
	runtimeCfg, err := ReadRuntimeConfig()
	var endpoint string
	if err != nil {
		// Fall back to VPS default port 8443 (not 8080)
		endpoint = "http://127.0.0.1:8443/healthz"
	} else {
		endpoint = runtimeCfg.HealthEndpoint()
	}

	maxAttempts := 10
	for i := 0; i < maxAttempts; i++ {
		if err := checkHealthEndpoint(endpoint); err == nil {
			log.Info().Msg("Health check passed")
			return nil
		}

		log.Info().Int("attempt", i+1).Int("max", maxAttempts).Msg("Waiting for service to become healthy...")

		// Sleep with exponential backoff
		sleepTime := (1 << uint(i)) * 100 // 100ms, 200ms, 400ms, ...
		if sleepTime > 5000 {
			sleepTime = 5000
		}

		exec.Command("sleep", fmt.Sprintf("0.%d", sleepTime/100)).Run()
	}

	return fmt.Errorf("service failed to become healthy after %d attempts", maxAttempts)
}

// checkHealthEndpoint checks the /healthz endpoint at the given URL.
func checkHealthEndpoint(endpoint string) error {
	cmd := exec.Command("curl", "-sf", "-m", "2", endpoint)
	cmd.Stdout = &bytes.Buffer{}
	cmd.Stderr = &bytes.Buffer{}
	return cmd.Run()
}

// RestartService restarts the orvixpanel service.
func RestartService() error {
	log.Info().Msg("Restarting orvixpanel service...")

	// Stop
	if err := stopService(); err != nil {
		return fmt.Errorf("stop: %w", err)
	}

	// Start
	if err := startService(); err != nil {
		return fmt.Errorf("start: %w", err)
	}

	// Wait for healthy
	return VerifyHealth()
}