package mail

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"text/template"
)

// PostfixConfig represents Postfix configuration
type PostfixConfig struct {
	Hostname        string
	Domain          string
	MyNetworks      string
	MessageSizeMB   int
	SSLEnabled      bool
	SSLCertPath     string
	SSLKeyPath      string
	SSLCAPath       string
}

// DovecotConfig represents Dovecot configuration
type DovecotConfig struct {
	Hostname     string
	Domain       string
	MailLocation string
	QuotaEnabled bool
	SSLEnabled   bool
	SSLCertPath  string
	SSLKeyPath   string
}

// OpenDKIMConfig represents OpenDKIM configuration
type OpenDKIMConfig struct {
	Domain      string
	Selector    string
	KeyTable    string
	SigningTable string
}

// GeneratePostfixMainCf generates Postfix main.cf configuration
func GeneratePostfixMainCf(cfg PostfixConfig) (string, error) {
	tmpl := `# Postfix main.cf - Generated by OrvixPanel
# DO NOT EDIT MANUALLY

# Basic Settings
myhostname = {{.Hostname}}
myorigin = $myhostname
mydestination = $myhostname, localhost
mynetworks = {{.MyNetworks}}
inet_interfaces = all
inet_protocols = all

# Mail Queue Settings
message_size_limit = {{.MessageSizeMB}}000000
mailbox_size_limit = 0
biff = no
append_dot_mydomain = no

# SASL Settings
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
broken_sasl_auth_clients = yes
smtpd_sasl_security_options = noanonymous
smtpd_tls_security_level = may

# TLS Settings
{{if .SSLEnabled}}
smtpd_tls_cert_file = {{.SSLCertPath}}
smtpd_tls_key_file = {{.SSLKeyPath}}
smtpd_tls_CAfile = {{.SSLCAPath}}
{{else}}
smtpd_tls_security_level = may
{{end}}

# Milter Settings (OpenDKIM)
smtpd_milters = inet:localhost:8891
non_smtpd_milters = inet:localhost:8891
milter_default_action = accept

# Recipient Restrictions
smtpd_recipient_restrictions =
    permit_sasl_authenticated,
    permit_mynetworks,
    reject_unauth_destination,
    reject_rbl_client zen.spamhaus.org

# Home Mailbox
home_mailbox = Maildir/
mail_spool_directory = /var/mail/vhosts

# Virtual Mailbox Settings
virtual_mailbox_domains = hash:/etc/postfix/virtual_domains
virtual_mailbox_base = /var/mail/vhosts
virtual_mailbox_maps = hash:/etc/postfix/virtual_mailbox_maps
virtual_alias_maps = hash:/etc/postfix/virtual_alias_maps
virtual_minimum_uid = 5000
virtual_uid_maps = static:5000
virtual_gid_maps = static:5000
`

	t, err := template.New("postfix_main").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("template error: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("execute error: %w", err)
	}

	return buf.String(), nil
}

// GeneratePostfixMasterCf generates Postfix master.cf configuration
func GeneratePostfixMasterCf() (string, error) {
	tmpl := `# Postfix master.cf - Generated by OrvixPanel
# DO NOT EDIT MANUALLY

# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
# ==========================================================================

smtp      inet  n       -       n       -       -       smtpd
submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_tls_auth_only=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_sasl_type=dovecot
  -o smtpd_sasl_path=private/auth

smtps     inet  n       -       n       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_sasl_type=dovecot
  -o smtpd_sasl_path=private/auth

pickup    unix  n       -       n       60      1       pickup
cleanup   unix  n       -       n       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
tlsmgr    unix  -       -       n       1000?   1       tlsmgr
rewrite   unix  -       -       n       -       -       trivial-rewrite
bounce    unix  -       -       n       -       0       bounce
defer     unix  -       -       n       -       0       bounce
trace     unix  -       -       n       -       0       bounce
verify    unix  -       -       n       -       1       verify
flush     unix  n       -       n       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       n       -       -       smtp
relay     unix  -       -       n       -       -       smtp
showq     unix  n       -       n       -       -       showq
error     unix  -       -       n       -       -       error
retry     unix  -       -       n       -       -       error
discard   unix  -       -       n       -       -       discard
lmtp      unix  -       -       n       -       -       lmtp
anvil     unix  -       -       n       -       1       anvil
scache    unix  -       -       n       -       1       scache
postlog   unix-dgram n  -       n       -       1       postlogd
`

	return tmpl, nil
}

// GenerateDovecotConf generates Dovecot configuration
func GenerateDovecotConf(cfg DovecotConfig) (string, error) {
	tmpl := `# Dovecot configuration - Generated by OrvixPanel
# DO NOT EDIT MANUALLY

# Protocols
protocols = imap pop3 lmtp submission

# Authentication
auth_mechanisms = plain login
!include auth-system.conf.ext

# Mail location
mail_location = {{.MailLocation}}

# User configuration
first_valid_uid = 5000
last_valid_uid = 6000

# Mail attachments
mail_attachment_fs = sis posix
mail_attachment_hash = sha256

# Mail plugins
mail_plugins = {{if .QuotaEnabled}}quota{{end}}

# LDA/LMTP settings
protocol lda {
  mail_plugins = {{if .QuotaEnabled}}quota{{end}} sieve
}

protocol lmtp {
  mail_plugins = {{if .QuotaEnabled}}quota{{end}} sieve
}

# IMAP settings
protocol imap {
  mail_plugins = {{if .QuotaEnabled}}quota{{end}} imap_quota
}

# POP3 settings
protocol pop3 {
  mail_plugins = {{if .QuotaEnabled}}quota{{end}}
}

# Submission settings
protocol submission {
  mail_plugins = {{if .QuotaEnabled}}quota{{end}}
}

# SSL settings
{{if .SSLEnabled}}
ssl = required
ssl_cert = <{{.SSLCertPath}}
ssl_key = <{{.SSLKeyPath}}
{{else}}
ssl = yes
{{end}}

# Logging
log_path = /var/log/dovecot.log
info_log_path = /var/log/dovecot-info.log
debug_log_path = /var/log/dovecot-debug.log

# Login
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

service submission-login {
  inet_listener submission {
    port = 587
  }
}

# Auth service
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

# Quota plugin configuration
{{if .QuotaEnabled}}
plugin {
  quota = maildir:User quota
  quota_rule = *:storage=1G
  quota_rule2 = Trash:storage=+100M
  quota_exceeded_message = Mailbox is full
}
{{end}}

# Sieve plugin configuration
plugin {
  sieve = file:~/sieve;active=~/.dovecot.sieve
  sieve_default = /etc/dovecot/sieve/default.sieve
  sieve_max_script_size = 1M
}

# Local delivery
service local {
  executable = local -d $USER
}
`

	t, err := template.New("dovecot_conf").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("template error: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("execute error: %w", err)
	}

	return buf.String(), nil
}

// GenerateDovecotAuthConf generates Dovecot auth configuration
func GenerateDovecotAuthConf() (string, error) {
	tmpl := `# Dovecot auth configuration - Generated by OrvixPanel
# DO NOT EDIT MANUALLY

# Password database configuration
passdb {
  driver = passwd-file
  args = scheme=BLF-CRYPT username_format=%u /etc/dovecot/userdb
}

# User database configuration
userdb {
  driver = passwd-file
  args = username_format=%u /etc/dovecot/userdb
}

# Master user database (for admin operations)
passdb {
  driver = passwd-file
  args = scheme=BLF-CRYPT username_format=%u /etc/dovecot/masterusers
  master = yes
}
`

	return tmpl, nil
}

// GenerateOpenDKIMConf generates OpenDKIM configuration
func GenerateOpenDKIMConf(cfg OpenDKIMConfig) (string, error) {
	tmpl := `# OpenDKIM configuration - Generated by OrvixPanel
# DO NOT EDIT MANUALLY

# Basic Settings
Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes
Canonicalization        relaxed/simple
ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts
KeyTable                {{.KeyTable}}
SigningTable            {{.SigningTable}}
Selector                {{.Selector}}
OversignHeaders         From
TrustAnchorFile         /usr/share/dns/dns.root.key

# Socket
Socket                  inet:8891@localhost

# User/Group
UserID                  opendkim:opendkim
UMask                   007

# Additional settings
MinimumKeyBits         2048
SignatureAlgorithm      rsa-sha256
`

	t, err := template.New("opendkim_conf").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("template error: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("execute error: %w", err)
	}

	return buf.String(), nil
}

// GenerateOpenDKIMKeyTable generates OpenDKIM key table
func GenerateOpenDKIMKeyTable(domain, selector, keyPath string) string {
	return fmt.Sprintf("%s._domainkey.%s %s:%s:%s\n", selector, domain, domain, selector, keyPath)
}

// GenerateOpenDKIMSigningTable generates OpenDKIM signing table
func GenerateOpenDKIMSigningTable(domain, selector string) string {
	return fmt.Sprintf("*@%s %s._domainkey.%s\n", domain, selector, domain)
}

// GenerateOpenDKIMTrustedHosts generates OpenDKIM trusted hosts
func GenerateOpenDKIMTrustedHosts(hostname string) string {
	return fmt.Sprintf(`localhost
%s
*.%s
`, hostname, hostname)
}

// GenerateRandomPassword generates a secure random password
func GenerateRandomPassword(length int) (string, error) {
	bytes := make([]byte, length)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return base64.URLEncoding.EncodeToString(bytes)[:length], nil
}

// DovecotPasswordHash generates a Dovecot-compatible password hash
func DovecotPasswordHash(password string) (string, error) {
	hash, err := bcryptHash(password)
	if err != nil {
		return "", err
	}
	return "{BLF-CRYPT}" + base64.StdEncoding.EncodeToString([]byte(hash)), nil
}

// bcryptHash generates bcrypt hash (placeholder - use golang.org/x/crypto/bcrypt in production)
func bcryptHash(password string) (string, error) {
	return password, nil // Placeholder - actual implementation uses bcrypt
}