package mail

import (
	"fmt"
	"os"
	"path/filepath"
)

// InstallerConfig represents mail installation configuration
type InstallerConfig struct {
	Enabled         bool
	Hostname        string
	AdminEmail      string
	SSLCertPath     string
	SSLKeyPath      string
	SSLCAPath       string
	MessageSizeMB   int
	StorageDir      string
}

// MailInstaller handles mail system installation
type MailInstaller struct {
	config *InstallerConfig
}

// NewMailInstaller creates a new mail installer
func NewMailInstaller(config *InstallerConfig) *MailInstaller {
	return &MailInstaller{config: config}
}

// Validate validates the installer configuration
func (i *MailInstaller) Validate() error {
	if !i.config.Enabled {
		return nil
	}

	if i.config.Hostname == "" {
		return fmt.Errorf("mail hostname is required when mail is enabled")
	}

	if i.config.AdminEmail == "" {
		return fmt.Errorf("admin email is required when mail is enabled")
	}

	return nil
}

// GenerateConfigs generates all mail configuration files
func (i *MailInstaller) GenerateConfigs(configDir string) error {
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Generate Postfix main.cf
	postfixConfig := PostfixConfig{
		Hostname:      i.config.Hostname,
		MyNetworks:    "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128",
		MessageSizeMB: i.config.MessageSizeMB,
		SSLEnabled:    i.config.SSLCertPath != "",
		SSLCertPath:   i.config.SSLCertPath,
		SSLKeyPath:    i.config.SSLKeyPath,
		SSLCAPath:     i.config.SSLCAPath,
	}

	postfixMain, err := GeneratePostfixMainCf(postfixConfig)
	if err != nil {
		return fmt.Errorf("failed to generate postfix main.cf: %w", err)
	}

	if err := os.WriteFile(filepath.Join(configDir, "postfix-main.cf"), []byte(postfixMain), 0600); err != nil {
		return fmt.Errorf("failed to write postfix main.cf: %w", err)
	}

	// Generate Postfix master.cf
	postfixMaster, err := GeneratePostfixMasterCf()
	if err != nil {
		return fmt.Errorf("failed to generate postfix master.cf: %w", err)
	}

	if err := os.WriteFile(filepath.Join(configDir, "postfix-master.cf"), []byte(postfixMaster), 0600); err != nil {
		return fmt.Errorf("failed to write postfix master.cf: %w", err)
	}

	// Generate Dovecot config
	dovecotConfig := DovecotConfig{
		Hostname:     i.config.Hostname,
		MailLocation: "maildir:~/Maildir",
		QuotaEnabled: true,
		SSLEnabled:   i.config.SSLCertPath != "",
		SSLCertPath:  i.config.SSLCertPath,
		SSLKeyPath:   i.config.SSLKeyPath,
	}

	dovecotConf, err := GenerateDovecotConf(dovecotConfig)
	if err != nil {
		return fmt.Errorf("failed to generate dovecot.conf: %w", err)
	}

	if err := os.WriteFile(filepath.Join(configDir, "dovecot.conf"), []byte(dovecotConf), 0600); err != nil {
		return fmt.Errorf("failed to write dovecot.conf: %w", err)
	}

	// Generate Dovecot auth config
	dovecotAuth, err := GenerateDovecotAuthConf()
	if err != nil {
		return fmt.Errorf("failed to generate dovecot auth config: %w", err)
	}

	if err := os.WriteFile(filepath.Join(configDir, "dovecot-auth.conf"), []byte(dovecotAuth), 0600); err != nil {
		return fmt.Errorf("failed to write dovecot auth config: %w", err)
	}

	// Generate OpenDKIM config
	opendkimConfig := OpenDKIMConfig{
		Domain:       i.config.Hostname,
		Selector:     "default",
		KeyTable:    "/etc/opendkim/KeyTable",
		SigningTable: "/etc/opendkim/SigningTable",
	}

	opendkimConf, err := GenerateOpenDKIMConf(opendkimConfig)
	if err != nil {
		return fmt.Errorf("failed to generate opendkim.conf: %w", err)
	}

	if err := os.WriteFile(filepath.Join(configDir, "opendkim.conf"), []byte(opendkimConf), 0600); err != nil {
		return fmt.Errorf("failed to write opendkim.conf: %w", err)
	}

	return nil
}

// CreateDirectories creates mail storage directories
func (i *MailInstaller) CreateDirectories(storageDir string) error {
	dirs := []string{
		filepath.Join(storageDir, "vhosts"),
		filepath.Join(storageDir, "quota"),
		filepath.Join(storageDir, "dkim"),
		filepath.Join(storageDir, "sieve"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	return nil
}

// GenerateSetupScript generates the mail setup shell script
func (i *MailInstaller) GenerateSetupScript(scriptPath string) error {
	script := `#!/bin/bash
# Mail system setup script - Generated by OrvixPanel
# This script installs and configures Postfix + Dovecot + OpenDKIM

set -e

echo "=== OrvixPanel Mail System Setup ==="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root"
    exit 1
fi

# Detect OS
if [ -f /etc/debian_version ]; then
    OS="debian"
elif [ -f /etc/redhat-release ]; then
    OS="rhel"
elif [ -f /etc/almalinux-release ]; then
    OS="rhel"
else
    echo "Error: Unsupported OS"
    exit 1
fi

echo "Detected OS: $OS"

# Install packages
echo "Installing mail packages..."

if [ "$OS" = "debian" ]; then
    apt-get update
    apt-get install -y postfix dovecot-core dovecot-imapd dovecot-pop3d dovecot-lmtpd opendkim opendkim-tools
elif [ "$OS" = "rhel" ]; then
    dnf install -y postfix dovecot opendkim
fi

echo "Packages installed successfully"

# Create vmail user
if ! id -u vmail > /dev/null 2>&1; then
    groupadd -g 5000 vmail
    useradd -g vmail -u 5000 -d /var/mail/vhosts -s /sbin/nologin vmail
fi

echo "Created vmail user (uid=5000, gid=5000)"

# Create directories
mkdir -p /var/mail/vhosts
mkdir -p /var/mail/quota
mkdir -p /var/mail/dkim
mkdir -p /var/mail/sieve
chown -R vmail:vmail /var/mail/vhosts
chmod -R 755 /var/mail

echo "Created mail directories"

# Generate DKIM keys directory
mkdir -p /etc/opendkim/keys
chown opendkim:opendkim /etc/opendkim/keys
chmod 700 /etc/opendkim/keys

echo "Created DKIM directories"

# Copy configuration files
# (Configuration files are generated separately by OrvixPanel)
echo ""
echo "=== Configuration ==="
echo "Please run OrvixPanel to generate mail configurations"
echo "Configs should be placed in:"
echo "  - /etc/postfix/main.cf (use postconf -e or copy from OrvixPanel output)"
echo "  - /etc/dovecot/dovecot.conf"
echo "  - /etc/opendkim.conf"

# Setup database
echo ""
echo "=== Database Setup ==="
echo "Run database migrations for mail tables:"

cat << 'SQL'
-- Add to your database migration
CREATE TABLE IF NOT EXISTS mail_domains (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(36) NOT NULL,
    domain VARCHAR(255) NOT NULL UNIQUE,
    dkim_selector VARCHAR(63) DEFAULT 'default',
    dkim_private TEXT,
    dkim_public TEXT,
    spf_record VARCHAR(255),
    dmarc_policy VARCHAR(50) DEFAULT 'v=none',
    is_catch_all BOOLEAN DEFAULT FALSE,
    max_mailboxes INT DEFAULT 100,
    status VARCHAR(20) DEFAULT 'active',
    created_by VARCHAR(36),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_mail_domains_tenant (tenant_id)
);

CREATE TABLE IF NOT EXISTS mailboxes (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(36) NOT NULL,
    mail_domain_id VARCHAR(36) NOT NULL,
    local_part VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    quota_mb INT DEFAULT 1024,
    quota_used_mb INT DEFAULT 0,
    enable_imap BOOLEAN DEFAULT TRUE,
    enable_pop3 BOOLEAN DEFAULT FALSE,
    enable_smtp BOOLEAN DEFAULT TRUE,
    status VARCHAR(20) DEFAULT 'active',
    last_login_at TIMESTAMP,
    created_by VARCHAR(36),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_mailboxes_tenant (tenant_id),
    INDEX idx_mailboxes_domain (mail_domain_id)
);

-- ... (add other tables similarly)
SQL

echo ""
echo "=== Setup Complete ==="
echo "Next steps:"
echo "1. Review and copy mail configurations"
echo "2. Run database migrations"
echo "3. Start services: systemctl start postfix dovecot opendkim"
echo "4. Enable services: systemctl enable postfix dovecot opendkim"
echo "5. Test with: telnet localhost 25"
echo ""
`

	if err := os.WriteFile(scriptPath, []byte(script), 0755); err != nil {
		return fmt.Errorf("failed to write setup script: %w", err)
	}

	return nil
}

// PrintInstallationGuide prints the installation guide
func PrintInstallationGuide() {
	fmt.Print(`
=== OrvixPanel Mail System Installation Guide ===

PREREQUISITES:
- Postfix 3.5+
- Dovecot 2.3+
- OpenDKIM 2.11+

INSTALLATION STEPS:

1. Install packages:

   Debian/Ubuntu:
   apt-get install postfix dovecot-core dovecot-imapd dovecot-pop3d dovecot-lmtpd opendkim opendkim-tools

   RHEL/CentOS:
   dnf install postfix dovecot opendkim

2. Create vmail user:

   groupadd -g 5000 vmail
   useradd -g vmail -u 5000 -d /var/mail/vhosts -s /sbin/nologin vmail

3. Create directories:

   mkdir -p /var/mail/vhosts /var/mail/quota /var/mail/dkim /var/mail/sieve
   chown -R vmail:vmail /var/mail/vhosts

4. Configure Postfix:

   # Copy generated postfix-main.cf to /etc/postfix/main.cf
   # Or use: postconf -e "parameter=value"

5. Configure Dovecot:

   # Copy generated dovecot.conf to /etc/dovecot/dovecot.conf

6. Configure OpenDKIM:

   # Copy generated opendkim.conf to /etc/opendkim.conf
   # Create key directory: mkdir -p /etc/opendkim/keys
   # Generate domain keys: opendkim-genkey -D /etc/opendkim/keys -d example.com -s default

7. Start services:

   systemctl start postfix dovecot opendkim
   systemctl enable postfix dovecot opendkim

8. Test configuration:

   # SMTP test
   telnet localhost 25
   EHLO localhost
   QUIT

   # IMAP test
   telnet localhost 143
   A001 LOGIN user@example.com password
   A001 LOGOUT

9. Verify DNS records:

   # SPF record
   dig TXT example.com +short

   # DKIM record
   opendkim-testkey -d example.com -s default

   # DMARC record
   dig TXT _dmarc.example.com +short

VERIFICATION:
After VPS installation, run:
  bash scripts/smoke-mail-local.sh

For more information, see docs/MAIL_INSTALLATION.md
`)
}