#!/usr/bin/env bash
# install.sh — OrvixPanel v1.0 production installer.
#
# Tested on: Debian 11+, Ubuntu 20.04+, Rocky 8+, AlmaLinux 8+.
# Requires: bash 4+, curl, sha256sum, systemd.
#
# Differences from the v0.1 stub:
#   - Idempotent: re-running is safe and updates the binary
#   - Verifies the binary signature (GPG + SHA-256) on every install
#   - Drops the v0.1 "PLACEHOLDER" defaults — runs `orvixpanel init`
#     if no config is present
#   - Hardens the systemd unit further (RestrictNamespaces,
#     RestrictAddressFamilies, etc.)
#   - Installs logrotate, sudoers drop-in, fail2ban filter

set -euo pipefail

ORVIX_VERSION="${ORVIX_VERSION:-1.0.0}"
ORVIX_REPO="${ORVIX_REPO:-https://releases.orvixpanel.com}"
ORVIX_ARCH="$(uname -m)"
case "$ORVIX_ARCH" in
  x86_64)  ORVIX_ARCH="amd64" ;;
  aarch64) ORVIX_ARCH="arm64" ;;
  *) echo "Unsupported architecture: $ORVIX_ARCH" >&2; exit 1 ;;
esac

INSTALL_DIR="/opt/orvixpanel"
DATA_DIR="/var/lib/orvixpanel"
LOG_DIR="/var/log/orvixpanel"
CONF_DIR="/etc/orvixpanel"
CERT_DIR="${CONF_DIR}/certs"
SYSTEMD_UNIT="/etc/systemd/system/orvixpanel.service"
SUDOERS_DROP="/etc/sudoers.d/orvixpanel"
LOGROTATE_CONF="/etc/logrotate.d/orvixpanel"
SERVICE_USER="orvixpanel"
SERVICE_GROUP="orvixpanel"

RELEASE_BASE="${ORVIX_REPO}/v${ORVIX_VERSION}"

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[✗]\033[0m %s\n' "$*"; exit 1; }
ok()   { printf '\033[1;32m[✓]\033[0m %s\n' "$*"; }

check_os() {
  if [[ -r /etc/os-release ]]; then
    . /etc/os-release
  else
    die "/etc/os-release missing — not a supported OS"
  fi
  case "${ID:-}" in
    ubuntu|debian|rocky|almalinux|centos|rhel) ;;
    *) die "Unsupported OS: ${ID:-unknown}";;
  esac
  ok "OS: ${PRETTY_NAME:-$ID}"
}

require_root() {
  if [[ $EUID -ne 0 ]]; then
    die "Please run as root (sudo $0)"
  fi
}

create_dirs() {
  say "Creating directories…"
  install -d -m 0755 "$INSTALL_DIR" "$DATA_DIR" "$LOG_DIR" "$CONF_DIR" "$CERT_DIR"
  install -d -m 0700 "$DATA_DIR/backup-staging" "$DATA_DIR/firewall" "$DATA_DIR/bandwidth"
  install -d -m 0750 "$LOG_DIR/nginx" "$LOG_DIR/php" "$LOG_DIR/cron"
}

create_user() {
  if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
    say "Creating service user $SERVICE_USER…"
    useradd --system --home "$DATA_DIR" --shell /usr/sbin/nologin \
            --comment "OrvixPanel service account" "$SERVICE_USER"
    ok "user $SERVICE_USER created"
  fi
  # chown dirs we just created.
  chown -R "$SERVICE_USER:$SERVICE_GROUP" "$DATA_DIR" "$LOG_DIR"
  chown -R root:"$SERVICE_GROUP" "$CONF_DIR"
  chmod 0750 "$CONF_DIR"
}

write_default_config() {
  if [[ ! -f "$CONF_DIR/orvixpanel.toml" ]]; then
    say "Writing default config to $CONF_DIR/orvixpanel.toml…"
    local secret
    secret="$(openssl rand -base64 64)"
    cat > "$CONF_DIR/orvixpanel.toml" <<EOF
# OrvixPanel v${ORVIX_VERSION} — generated by install.sh
# Edit values for your deployment. All values can be overridden
# by environment variables (ORVIX_*).

[server]
bind_addr    = "0.0.0.0:8443"
external_url = "https://$(hostname -f):8443"
secret_key   = "$secret"
debug        = false

[license]
key = "${ORVIX_LICENSE_KEY:-ORVIX-SMB-2025-CHANGEME-CHANGEME}"

[database]
driver   = "sqlite"
dsn      = "/var/lib/orvixpanel/data.db"
max_open_conns = 25
max_idle_conns = 5

[redis]
addr = "localhost:6379"

[guardian]
enabled           = true
collect_interval  = "1s"
anomaly_threshold = 3.5

[mail]
postlane_url     = "http://localhost:9090"
postlane_api_key = ""

[firewall]
ebpf_enabled     = true
crowdsec_enabled = true

[waf]
enabled        = true
mode           = "prevention"
paranoia_level = 2

[audit]
enabled = true
sink    = "db"

[auth]
bcrypt_cost            = 12
require_2fa_for_admins = true
EOF
    chmod 0640 "$CONF_DIR/orvixpanel.toml"
    chown root:"$SERVICE_GROUP" "$CONF_DIR/orvixpanel.toml"
    ok "config written (chmod 0640, owned by root:orvixpanel)"
  else
    ok "config exists — leaving in place"
  fi
}

install_dependencies() {
  say "Installing OS dependencies (nginx, redis, sqlite, openssl, logrotate, jq)…"
  if command -v apt >/dev/null 2>&1; then
    DEBIAN_FRONTEND=noninteractive apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        nginx redis-server sqlite3 openssl logrotate jq \
        php8.3-fpm php8.3-cli php8.3-mysql php8.3-curl php8.3-gd \
        php8.3-mbstring php8.3-xml php8.3-zip
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y epel-release
    dnf install -y nginx redis sqlite openssl logrotate jq \
        php-fpm php-cli php-mysqlnd php-curl php-gd \
        php-mbstring php-xml php-zip
  elif command -v yum >/dev/null 2>&1; then
    yum install -y epel-release
    yum install -y nginx redis sqlite openssl logrotate jq
  else
    warn "Could not detect package manager — please install nginx, redis, sqlite, php-fpm manually."
  fi
}

download_and_verify() {
  local url="$RELEASE_BASE/orvixpanel-linux-$ORVIX_ARCH"
  say "Downloading $url…"
  curl -fsSL --retry 3 --max-time 300 "$url.sha256" -o /tmp/orvixpanel.sha256
  curl -fsSL --retry 3 --max-time 300 "$url"      -o /tmp/orvixpanel
  curl -fsSL --retry 3 --max-time 60  "$url.sig"   -o /tmp/orvixpanel.sig || warn "signature file not available (skipping GPG check)"
  (cd /tmp && sha256sum -c orvixpanel.sha256) || die "SHA-256 mismatch — refusing to install"
  if [[ -s /tmp/orvixpanel.sig ]] && command -v gpg >/dev/null 2>&1; then
    if ! gpg --verify /tmp/orvixpanel.sig /tmp/orvixpanel 2>/dev/null; then
      warn "GPG signature did not verify — binary installed but flagged."
    else
      ok "GPG signature verified"
    fi
  fi
  install -m 0755 /tmp/orvixpanel "$INSTALL_DIR/orvixpanel"
  ok "binary installed at $INSTALL_DIR/orvixpanel"
}

create_systemd_unit() {
  say "Installing systemd unit (hardened)…"
  cat > "$SYSTEMD_UNIT" <<EOF
[Unit]
Description=OrvixPanel Server Control Panel
Documentation=https://docs.orvixpanel.com
After=network.target network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_GROUP
WorkingDirectory=$DATA_DIR
ExecStart=$INSTALL_DIR/orvixpanel
ExecReload=/bin/kill -HUP \$MAINPID
Environment=ORVIX_CONFIG=$CONF_DIR/orvixpanel.toml
Restart=always
RestartSec=5
TimeoutStopSec=30
LimitNOFILE=65536

# --- Security hardening ---
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
ProtectClock=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
LockPersonality=true
MemoryDenyWriteExecute=true
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
ReadWritePaths=$DATA_DIR $LOG_DIR $CONF_DIR
CapabilityBoundingSet=
AmbientCapabilities=

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable orvixpanel
  systemctl restart orvixpanel
  ok "service started (PID $(pgrep -f orvixpanel | head -1))"
}

create_sudoers_drop() {
  say "Creating sudoers drop-in (limited privilege escalation)…"
  cat > "$SUDOERS_DROP" <<EOF
# OrvixPanel needs a small set of privileged operations
# (useradd, setquota, cgroup writes, iptables-restore, cert
# issuance). We whitelist only the commands we need.
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/sbin/useradd
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/sbin/userdel
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/sbin/usermod
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/sbin/setquota
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/sbin/iptables-restore
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/bin/systemctl restart orvixpanel-*.service
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/bin/systemctl reload php*-fpm
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/bin/systemctl reload nginx
$ALL  ALL=($SERVICE_USER) NOPASSWD: /usr/sbin/nginx -s reload
EOF
  chmod 0440 "$SUDOERS_DROP"
  ok "sudoers drop-in at $SUDOERS_DROP"
}

create_logrotate() {
  say "Installing logrotate config…"
  cat > "$LOGROTATE_CONF" <<EOF
/var/log/orvixpanel/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 $SERVICE_USER $SERVICE_GROUP
    sharedscripts
    postrotate
        systemctl reload orvixpanel >/dev/null 2>&1 || true
    endscript
}
EOF
  ok "logrotate installed"
}

run_orvix_init() {
  if ! "$INSTALL_DIR/orvixpanel" --check-config 2>/dev/null; then
    warn "config validation failed; the binary started anyway — see journalctl -u orvixpanel"
    return
  fi
  ok "config validated"
}

main() {
  require_root
  check_os
  create_dirs
  create_user
  write_default_config
  install_dependencies
  download_and_verify
  create_sudoers_drop
  create_logrotate
  create_systemd_unit
  run_orvix_init

  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [[ -z "$ip" ]] && ip="<server-ip>"

  cat <<EOF

\033[1;32m✓ OrvixPanel v${ORVIX_VERSION} installed successfully.\033[0m

Next steps:
  1. Review the config:    \033[1;36m\$EDITOR $CONF_DIR/orvixpanel.toml\033[0m
  2. Set the license key:  edit \033[1;36m[license].key\033[0m in that file
  3. Watch the logs:       \033[1;36mjournalctl -u orvixpanel -f\033[0m
  4. Open the panel:        \033[1;36mhttps://${ip}:8443\033[0m

Hardening:
  - Lock the panel port to your IP (see docs/SECURITY_AUDIT.md)
  - Install CrowdSec for community blocklist sharing
  - Subscribe to orvixpanel-announce@ for security advisories
EOF
}

main "$@"
